base/urls.py
from django.urls import path

from .views import *

app_name = 'base'

urlpatterns = [
    path('', home, name = "home"),
    path('register/corporate', register, {'user_type': 'corporate'}, name = "register_corporate"),
    path('register', register, {'user_type': 'user'}, name = "register_user"),
    path('logout', logout_user, name = "logout_user"),
    path('login', login_user, name = "login_user"),
]

book_a_room/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve


handler404 = 'base.views.error_404_view'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('hotel/', include('hotel.urls')),
    path('user/', include('user.urls')),
    path('payment/', include('payment_gateway.urls')),
    re_path(r"^media/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT}),
    re_path(r"^static/(?P<path>.*)$", serve, {"document_root": settings.STATIC_ROOT}),
    path('summernote/', include('django_summernote.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

hotel/urls.py
from django.urls import path

from .views import home, hotel_dashboard, edit_hotel, delete_hotel, search_hotel, list_hotel, hotel_detail, update_total_cost, hotel_cart

app_name = 'hotel'

urlpatterns = [
    path('', home, name='home'),
    path('dashboard', hotel_dashboard, name='dashboard'),
    path('update/<slug>', edit_hotel, name='update'),
    path('delete/<slug>', delete_hotel, name='delete'),
    path("search", search_hotel, name="search"),
    path('list-hotel', list_hotel, name='list_hotel'),
    path('hotel-detail/<slug>', hotel_detail, name = 'hotel_detail'),
    path('update-tc/<slug>', update_total_cost, name = 'update_total_cost'),
    path('hotel-cart', hotel_cart, name = 'hotel_cart'),
    
]

payment_gateway/urls.py
from django.urls import path

from .views import create_stripe_checkout_session, payment_success, payment_cancel

app_name = "payment_gateway"

urlpatterns = [
    path(
        "create-checkout-session/<int:reservation_pk>",
        create_stripe_checkout_session,
        name="create-checkout-session-pk",
    ),
    path("success/<int:reservation_pk>", payment_success, name="payment_success"),
    path("cancel/<int:reservation_pk>", payment_cancel, name="payment_cancel"),
]

hotel/models.py
from django.db import models
from django.conf import settings
from decimal import Decimal
from django_summernote.fields import SummernoteTextField

from base.helper import generate_slug


# Create your models here.
class Hotel(models.Model):
    hotelier = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True
    )
    name = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    description = SummernoteTextField()
    price = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    slug = models.SlugField(max_length=255, null=True, blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.pk:
            self.slug = generate_slug(self.name)
        super(Hotel, self).save(*args, **kwargs)


class HotelImage(models.Model):
    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE, null=True)
    hotel_images = models.ImageField(upload_to="bookaroom/hotel_images/", null=True)

    def __str__(self):
        return f"Images for {self.hotel.name}"


class Reservation(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE)
    check_in_date = models.DateField(null = True)
    check_out_date = models.DateField(null = True)
    total_cost = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    is_paid = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Reservation for {self.user.username} in {self.hotel.name}"

    def calculate_total_cost(self):
        nights = (self.check_out_date - self.check_in_date).days

        return self.hotel.price * Decimal(nights)

hotel/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django_summernote.widgets import SummernoteWidget
from datetime import *

from .models import Hotel, HotelImage, Reservation


class HotelForm(forms.ModelForm):
    class Meta:
        model = Hotel
        fields = ["name", "address", "description", "price"]
        widgets = {
            "name": forms.TextInput(attrs={"class": "input-style"}),
            "address": forms.TextInput(attrs={"class": "input-style"}),
            "description": SummernoteWidget(),
            "price": forms.TextInput(
                attrs={"class": "input-style", "type": "number", "step": "0.01"}
            ),
        }
        
    def __init__(self, *args, **kwargs):
        super(HotelForm, self).__init__(*args, **kwargs)
        # Make the 'price' field not required
        self.fields["price"].required = False

    def clean(self):
        cleaned_data = super().clean()
        price = cleaned_data.get("price")

        if price is not None and price < 0:
            raise forms.ValidationError("Price must be a non-negative value")

        return cleaned_data


class HotelImageForm(forms.ModelForm):
    class Meta:
        model = HotelImage
        fields = ["hotel", "hotel_images"]


HotelImageFormSet = forms.inlineformset_factory(
    Hotel, HotelImage, form=HotelImageForm, extra=1, can_delete=True
)


class ReservationForm(forms.ModelForm):
    class Meta:
        model = Reservation
        fields = ["check_in_date", "check_out_date"]

        widgets = {
            "check_in_date": forms.DateInput(
                attrs={"type": "date", "class": "input-check_in"}
            ),
            "check_out_date": forms.DateInput(
                attrs={"type": "date", "class": "input-check_out"}
            ),
        }

    def clean_check_in_date(self):
        check_in_date = self.cleaned_data.get("check_in_date")

        # Check if check-in date is in the past
        if check_in_date < date.today():
            raise ValidationError("Check-in date must be in the future.")

        return check_in_date

    def clean(self):
        super().clean()

        # Ensure check-out date is after check-in date
        check_in_date = self.cleaned_data.get("check_in_date")
        check_out_date = self.cleaned_data.get("check_out_date")

        if check_out_date <= check_in_date:
            raise ValidationError("Check-out date must be after check-in date.")

        return self.cleaned_data

hotel/views.py
from django.shortcuts import render, get_object_or_404, redirect, HttpResponse
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from datetime import date, timedelta
from django.db.models import Q
from django.utils import timezone

from .models import Hotel, HotelImage, Reservation
from .forms import HotelForm, HotelImageFormSet, ReservationForm


# Create your views here.
def home(request):
    hotels = Hotel.objects.all()

    context = {"hotels": hotels}
    return render(request, "hotel/index.html", context)


def list_hotel(request):
    if request.method == "POST":
        hotel_form = HotelForm(request.POST)
        hotelimg_form = HotelImageFormSet(request.POST, request.FILES)

        if hotel_form.is_valid() and hotelimg_form.is_valid():
            hotel = hotel_form.save(commit=False)
            hotel.hotelier = request.user
            hotel.save()

            hotelimg_form.instance = hotel
            hotelimg_form.save()

            return redirect("hotel:hotel_detail", hotel.slug)

    else:
        hotel_form = HotelForm()
        hotelimg_form = HotelImageFormSet(instance=None)

    context = {
        "hotel_form": hotel_form,
        "hotelimg_form": hotelimg_form,
    }
    return render(request, "hotel/listing_hotel.html", context)


def hotel_detail(request, slug):
    hotel = get_object_or_404(Hotel, slug=slug)
    hotel_images = HotelImage.objects.filter(hotel=hotel)
    image_urls = [image.hotel_images.url for image in hotel_images]

    if request.method == "POST":
        reservation_form = ReservationForm(request.POST)
        if reservation_form.is_valid():
            reservation = reservation_form.save(commit=False)
            reservation.hotel = hotel
            reservation.user = request.user  # Assign the current user
            reservation.total_cost = (
                reservation.calculate_total_cost()
            )  # Calculate total cost
            reservation.save()

            pending_reservations = Reservation.objects.filter(user = request.user, hotel=hotel, is_paid=False)
            if len(pending_reservations) > 1:
                return redirect("hotel:hotel_cart")

            return redirect("payment_gateway:create-checkout-session-pk", reservation_pk = reservation.pk)
        
    else:
        reservation_form = ReservationForm()

    context = {
        "hotel": hotel,
        "reservation_form": reservation_form,
        "image_urls": image_urls,
        "login_message": "Please log in to make a reservation",
    }
    return render(request, "hotel/hotel_detail.html", context)


@csrf_exempt
@require_POST
def update_total_cost(request, slug=None, pk=None):
    form = ReservationForm(request.POST)
    if form.is_valid():
        try:
            reservation_hotel = Hotel.objects.get(slug=slug)
        except Hotel.DoesNotExist:
            return JsonResponse({"error": "Hotel does not exist."}, status=404)

        reservation = form.save(commit=False)
        reservation.hotel = reservation_hotel
        tc = reservation.calculate_total_cost()

        reservation.total_cost = tc

        return JsonResponse({"total_cost": "{:.2f}".format(tc)})
    else:
        return JsonResponse({"error": "Invalid form data"}, status=400)


def hotel_dashboard(request):
    if request.user.is_corporate:
        hotels = Hotel.objects.filter(hotelier__username=request.user.username)

        context = {"hotels": hotels}
        return render(request, "hotel/hotel_dashboard.html", context)


@login_required(login_url="login")
def edit_hotel(request, slug):
    hotel = get_object_or_404(Hotel, slug=slug)

    if request.method == "GET":
        hotel_form = HotelForm(instance=hotel)
        hotelimg_form = HotelImageFormSet(instance=hotel)
    else:
        hotel_form = HotelForm(request.POST, instance=hotel)
        hotelimg_form = HotelImageFormSet(request.POST, request.FILES, instance=hotel)

        if hotel_form.is_valid() and hotelimg_form.is_valid():
            hotel = hotel_form.save(commit=False)
            hotel.save()
            hotelimg_form.save()
            return redirect("hotel:hotel_detail", hotel.slug)
        else:
            # Handle formset validation errors if needed
            pass

    context = {
        "hotel_form": hotel_form,
        "hotelimg_form": hotelimg_form,
    }

    return render(request, "hotel/edit_hotel.html", context)


@login_required(login_url="login")
def delete_hotel(request, slug):
    hotel = get_object_or_404(Hotel, slug=slug)
    
    hotel_name = hotel.name

    if request.user.is_corporate:
        hotel.delete()

        context = {
            'hotel_name': hotel_name
        }

        return render(request, 'hotel/delete_hotel.html', context)


def search_hotel(request):
    query = request.GET.get("query", "")

    # Search for hotels based on the name, address, or description containing the query
    hotels = Hotel.objects.filter(
        Q(name__icontains=query)
        | Q(address__icontains=query)
        | Q(description__icontains=query)
    )

    context = {
        "hotels": hotels,
        "query": query,
    }

    return render(request, "hotel/search_result.html", context)


def hotel_cart(request):
    reservation_lst = Reservation.objects.filter(user=request.user, is_paid = False)

    context = {
        "reservation_lst": reservation_lst,
    }

    return render(request, "hotel/hotel_cart.html", context)

hotel/templates/hotel/delete_hotel.html
{% extends "base.html" %}


{% block title %}
    - Delete
{% endblock title %}
    


{% block content %}
    Successfully delete {{ hotel_name }}
{% endblock content %}
    

hotel/templates/hotel/edit_hotel.html
{% extends "base.html" %}


{% block content %}

<form action="" method = 'post' enctype="multipart/form-data">
    {% csrf_token %}

    {{ hotel_form.as_div }}

    <!-- Formset management form for handling hotel images -->
    {{ hotelimg_form.management_form }}

    <div class="hotel_images">
        <!-- Iterate over each form in the formset and render it -->
        {% for subform in hotelimg_form.forms %}
        {{ subform.as_div }}
        {% endfor %}
    </div>

    <button type="button" id="add-hotelimage-form">Add Hotel Image</button>

    <button class="button-style">Update</button>
</form>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        const formsetContainer = document.querySelector(".hotel_images");
        const addButton = document.getElementById("add-hotelimage-form");

        addButton.addEventListener("click", function () {
            const formCountInput = document.getElementById("id_hotelimage_set-TOTAL_FORMS");
            const formCount = parseInt(formCountInput.value);

            const newFormHtml = `
                <div>
                  <label for="id_hotelimage_set-${formCount}-hotel_images">Image:</label>
                  <input type="file" name="hotelimage_set-${formCount}-hotel_images" accept="image/*" id="id_hotelimage_set-${formCount}-hotel_images">
                </div>
                <div>
                  <label for="id_hotelimage_set-${formCount}-DELETE">Delete:</label>
                  <input type="checkbox" name="hotelimage_set-${formCount}-DELETE" id="id_hotelimage_set-${formCount}-DELETE">
                  <input type="hidden" name="hotelimage_set-${formCount}-id" id="id_hotelimage_set-${formCount}-id">
                  <input type="hidden" name="hotelimage_set-${formCount}-hotel" value="{{ hotel_form.instance.id }}" id="id_hotelimage_set-${formCount}-hotel">
                </div>`;

            formsetContainer.insertAdjacentHTML("beforeend", newFormHtml);
            formCountInput.value = formCount + 1;
        });
    });

</script>


{% endblock content %}
    

hotel/templates/hotel/hotel_cart.html
{% extends "base.html" %}


{% block content %}
<div class="reservations">
    <div class="heading">
        <p>Reservations</p>
    </div>
    <div class="records">
        <table>
            <tr>
                <th>Hotel</th>
                <th>Check-In Date</th>
                <th>Check-Out Date</th>
                <th>Total Cost</th>
                <th>Created At</th>
                <th>Action</th>
            </tr>
            {% if reservation_lst %}
            {% for reservation in reservation_lst %}
            <tr>
                <td>
                    <a href="{% url 'hotel:hotel_detail' reservation.hotel.slug %}">
                        {{ reservation.hotel }}
                    </a>
                </td>
                <td>{{ reservation.check_in_date }}</td>
                <td>{{ reservation.check_out_date }}</td>
                <td>{{ reservation.total_cost }}</td>
                <td>{{ reservation.created_at }}</td>
                <td>
                    <a href="{% url 'payment_gateway:create-checkout-session-pk' reservation_pk=reservation.pk %}">
                        <button class="button-style">Pay</button>
                    </a>

                    <a href="{% url 'payment_gateway:payment_cancel' reservation_pk=reservation.pk %}">
                        <button class="button-style">Cancel</button>
                    </a>
                </td>
            </tr>

            {% endfor %}

            {% else %}
            <tr>
                <td colspan="6">No reservation yet.</td>
            </tr>

            {% endif %}
        </table>

    </div>
</div>
{% endblock content %}

hotel/templates/hotel/hotel_dashboard.html
{% extends "base.html" %}


{% block title %}
-
{% endblock title %}


{% block content %}

<div class="hotel-cards">

    {% if request.user.is_corporate and hotels|length == 0 %}
    <div class="heading">
        <p>You haven' t listed any hotels yet.</p>
    </div>
    <a href="{% url 'hotel:list_hotel' %}" style="color: #2196F3;">List Your Hotel</a>
    {% endif %}
</div>

<ul>
    <div class="div-flex" style="flex-direction: column;">
        {% for hotel in hotels %}

        <div class="hotel-card">

            <li>

                <div class="hotel-pics div-flex">
                    {% for hotel_img in hotel.hotelimage_set.all %}
                    <div class="hotel-pic">
                        <img class="responsive-image" src="{{ hotel_img.hotel_images.url }}" alt="{{ hotel.name }}">
                    </div>
                    {% endfor %}
                </div>

                <div class="hotel-detail">

                    <p class="heading">
                        {{ hotel.name }}
                    </p>
                    <p class="hotel-info">
                        {{ hotel.address }}
                    </p>
                    <p class="hotel-info">
                        {{ hotel.description|safe }}
                    </p>
                    <p class="hotel-info price">
                        <span>
                            NPR
                            {{ hotel.price }}
                        </span>
                    </p>

                </div>

                <a href="{% url 'hotel:update' hotel.slug %}"><button class="button-style">Edit</button></a>
                <a href="{% url 'hotel:delete' hotel.slug %}"><button class="button-style"
                        style="background-color: #ba2121;">Delete</button></a>

            </li>
        </div>

        {% endfor %}

    </div>
</ul>
</div>


{% endblock content %}

hotel/templates/hotel/hotel_detail.html
{% extends "base.html" %}


{% block title %}
{{ hotel.name }} -
{% endblock title %}


{% block content %}

<div class="hotel-detail-wrapper">

    <div class="hotel-pics div-flex">
        {% for img_url in image_urls %}

        <div class="hotel-pic">
            <img class="responsive-image" src="{{ img_url }}" alt="{{ hotel.name }}">
        </div>

        {% endfor %}

    </div>

    <div class="info__booking div-flex">

        <div class="hotel-detail">

            <p class="heading">
                {{ hotel.name }}
            </p>
            <p class="hotel-info">
                {{ hotel.address }}
            <p class="hotel-info description">
                {{ hotel.description|safe }}
            </p>

        </div>
        {% if not request.user.is_corporate %}

        <form action="" method='post' id="reservation-form">
            {% csrf_token %}

            <input type="hidden" name="is_authenticated" value="{{ request.user.is_authenticated }}">

            {% if not request.user.is_authenticated %}
            <div class="login-msg">
                <p style="color: red; font-weight: 700">{{ login_message }}</p>
            </div>

            {% endif %}

            <div class="form-div position-sticky" style="top: 80px;">
                <div class="price-wrapper">
                    <p class="hotel-info price">
                        <span>
                            NPR
                            {{ hotel.price }}
                        </span>
                    </p>
                    <p style="margin: 0; font-size: 13px; color:#6d787d;">Inclusive of all taxes</p>
                </div>

                {{ reservation_form.as_p }}

                <div class="custom-hr"></div>

                <div class="div-flex total-cost-wrapper">
                    <div>
                        <p style="margin-bottom: 0;">Total price</p>
                        <span style="font-size: 13px; color:#6d787d;">(incl. of all taxes)</span>
                    </div>

                    <div>

                        <div class="threedotloader" id="loading-spinner" style="display: none;">
                            <div class='dot'></div>
                            <div class='dot'></div>
                            <div class='dot'></div>
                        </div>

                        <p id="total-cost" style="display: block;">{{ hotel.price }}</p>
                    </div>
                </div>

                <br>

                <button class="button-style">Continue Booking</button>
            </div>
        </form>

        {% endif %}

    </div>
</div>

<script>
    $(document).ready(function () {
        // Provide the predefine dates of today and tomorrow.
        const today = new Date().toISOString().split('T')[0];
        $(".input-check_in").attr("min", today).val(today);

        const tomorrow = new Date();
        tomorrow.setDate(tomorrow.getDate() + 1);
        const tomorrowDate = tomorrow.toISOString().split('T')[0];
        $(".input-check_out").attr("min", tomorrowDate).val(tomorrowDate);
    })

    $(document).ready(function () {
        // Attach the event listener to form inputs
        $('.input-check_in, .input-check_out').on('change', function () {
            // Show loading animation
            $('#loading-spinner').show();

            // Disable the submit button
            $('button.button-style').prop('disabled', true);

            $('#total-cost').hide();

            // Update total cost
            updateTotalCost();
        });


        // Function to update the total cost
        function updateTotalCost() {
            // Serialize form data
            var formData = $('#reservation-form').serialize();

            var url = '{% url "hotel:update_total_cost" hotel.slug %}';

            var isAuthenticated = $('#reservation-form input[name="is_authenticated"]').val();

            $.ajax({
                type: 'POST',
                url: url,
                data: formData,
                success: function (data) {
                    // Hide loading animation
                    $('#loading-spinner').hide();

                    $('#total-cost').show();

                    $('#total-cost').text(data.total_cost);

                    if (isAuthenticated === "True") {
                        $('button.button-style').prop('disabled', false);
                    }

                },
                error: function (error) {
                    console.log(error);
                    // Hide loading animation in case of an error
                    $('#loading-spinner').hide();
                }
            });
        }

    });

    // Disable the submit button when login message is displayed
    if ($('.login-msg').length > 0) {
        $('button.button-style').prop('disabled', true);

    }
</script>

{% endblock content %}

hotel/templates/hotel/hotels.html
<div class="hotel-cards">
    {% if request.user.is_corporate and hotels|length == 0 %}
    <div class="heading">
        <p>You haven't listed any hotels yet.</p>
    </div>
    <a href="{% url 'hotel:list_hotel' %}" style="color: #2196F3;">List Your Hotel</a>
    {% endif %}

    <ul class="div-flex" style="flex-wrap: wrap;">
        {% if hotels %}
        {% for hotel in hotels %}
        <div class="hotel-card">
            <a href="{% url 'hotel:hotel_detail' hotel.slug %}">
                <li>
                    <div class="hotel-pic">
                        <img class="responsive-image" src="{{ hotel.hotelimage_set.all.first.hotel_images.url }}" alt="{{ hotel.name }}">
                    </div>

                    <div class="hotel-detail">

                        <p class="heading">
                            {{ hotel.name }}
                        </p>
                        <p class="hotel-info">
                            {{ hotel.address }}
                        </p>
                        <p class="hotel-info price">
                            <span>
                                NPR
                                {{ hotel.price }}
                            </span>
                        </p>

                    </div>
                </li>
            </a>
        </div>
        {% endfor %}
        {% else %}
        <p>Hotels not found.</p>
        {% endif %}
    </ul>

</div>

hotel/templates/hotel/index.html
{% extends "base.html" %}


{% block title %}
    Hotels - 
{% endblock title %}
    

{% block content %}

{% include "./hotels.html" %}

{% endblock content %}

hotel/templates/hotel/listing_hotel.html
{% extends "base.html" %}


{% block content %}
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}

    {{ hotel_form.as_div }}

    <!-- Formset management form for handling hotel images -->
    {{ hotelimg_form.management_form }}

    <div class="hotel_images">
        <!-- Iterate over each form in the formset and render it -->
        {% for subform in hotelimg_form.forms %}
        {{ subform.as_div }}
        {% endfor %}
    </div>

    <button type="button" id="add-hotelimage-form">Add Hotel Image</button>
    <button class="button-style">Submit</button>
</form>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        const formsetContainer = document.querySelector(".hotel_images");
        const addButton = document.getElementById("add-hotelimage-form");

        addButton.addEventListener("click", function () {
            const formCountInput = document.getElementById("id_hotelimage_set-TOTAL_FORMS");
            const formCount = parseInt(formCountInput.value);

            const newFormHtml = `
                <div>
                  <label for="id_hotelimage_set-${formCount}-hotel_images">Image:</label>
                  <input type="file" name="hotelimage_set-${formCount}-hotel_images" accept="image/*" id="id_hotelimage_set-${formCount}-hotel_images">
                </div>
                <div>
                  <label for="id_hotelimage_set-${formCount}-DELETE">Delete:</label>
                  <input type="checkbox" name="hotelimage_set-${formCount}-DELETE" id="id_hotelimage_set-${formCount}-DELETE">
                  <input type="hidden" name="hotelimage_set-${formCount}-id" id="id_hotelimage_set-${formCount}-id">
                  <input type="hidden" name="hotelimage_set-${formCount}-hotel" value="{{ hotel_form.instance.id }}" id="id_hotelimage_set-${formCount}-hotel">
                </div>`;

            formsetContainer.insertAdjacentHTML("beforeend", newFormHtml);
            formCountInput.value = formCount + 1;
        });
    });

</script>
{% endblock content %}

hotel/templates/hotel/lst_hotel.html
{% extends "base.html" %}


{% block content %}
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}

    {{ hotel_form }}

    <!-- Formset management form for handling hotel images -->
    {{ hotelimg_form.management_form }}

    <div class="hotel_images">
        <!-- Iterate over each form in the formset and render it -->
        {% for subform in hotelimg_form.forms %}
        {{ subform.as_div }}
        {% endfor %}
    </div>

    <button type="button" id="add-hotelimage-form">Add Hotel Image</button>
    <button class="button-style">Submit</button>
</form>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        const formsetContainer = document.querySelector(".hotel_images");
        const addButton = document.getElementById("add-hotelimage-form");

        addButton.addEventListener("click", function () {
            const formCountInput = document.getElementById("id_hotelimage_set-TOTAL_FORMS");
            const formCount = parseInt(formCountInput.value);

            const newFormHtml = `
                <div>
                  <label for="id_hotelimage_set-${formCount}-hotel_images">Image:</label>
                  <input type="file" name="hotelimage_set-${formCount}-hotel_images" accept="image/*" id="id_hotelimage_set-${formCount}-hotel_images">
                </div>
                <div>
                  <label for="id_hotelimage_set-${formCount}-DELETE">Delete:</label>
                  <input type="checkbox" name="hotelimage_set-${formCount}-DELETE" id="id_hotelimage_set-${formCount}-DELETE">
                  <input type="hidden" name="hotelimage_set-${formCount}-id" id="id_hotelimage_set-${formCount}-id">
                  <input type="hidden" name="hotelimage_set-${formCount}-hotel" value="{{ hotel_form.instance.id }}" id="id_hotelimage_set-${formCount}-hotel">
                </div>`;

            formsetContainer.insertAdjacentHTML("beforeend", newFormHtml);
            formCountInput.value = formCount + 1;
        });
    });

</script>
{% endblock content %}

hotel/templates/hotel/search_result.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
Search Results for '{{ query }}'
{% endblock %}

{% block content %}

<h1>Search Results for "{{ query }}"</h1>



<div class="hotel-cards">
    {% if hotels %}

    <ul class="div-flex">
        {% for hotel in hotels %}
        <div class="hotel-card">
            <a href="{% url 'hotel:hotel_detail' hotel.slug %}">
                <li>
                    <div class="hotel-pic">
                        <img class="responsive-image" src="{{ hotel.hotelimage_set.all.first.hotel_images.url }}"
                            alt="{{ hotel.name }}">
                    </div>

                    <div class="hotel-detail">

                        <p class="heading">
                            {{ hotel.name }}
                        </p>
                        <p class="hotel-info">
                            {{ hotel.address }}
                        </p>
                        <p class="hotel-info price">
                            <span>
                                NPR
                                {{ hotel.price }}
                            </span>
                        </p>

                    </div>
                </li>
            </a>
        </div>
        {% endfor %}
    </ul>
    {% else %}
    <p>No hotels found for "{{ query }}".</p>
    {% endif %}

</div>
{% endblock %}