base/urls.py
from django.urls import path

from .views import *

app_name = 'base'

urlpatterns = [
    path('', home, name = "home"),
    path('register/corporate', register, {'user_type': 'corporate'}, name = "register_corporate"),
    path('register', register, {'user_type': 'user'}, name = "register_user"),
    path('logout', logout_user, name = "logout_user"),
    path('login', login_user, name = "login_user"),
]

book_a_room/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve


handler404 = 'base.views.error_404_view'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('hotel/', include('hotel.urls')),
    path('user/', include('user.urls')),
    path('payment/', include('payment_gateway.urls')),
    re_path(r"^media/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT}),
    re_path(r"^static/(?P<path>.*)$", serve, {"document_root": settings.STATIC_ROOT}),
    path('summernote/', include('django_summernote.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

hotel/urls.py
from django.urls import path

from .views import home, hotel_dashboard, edit_hotel, delete_hotel, search_hotel, list_hotel, hotel_detail, update_total_cost, hotel_cart

app_name = 'hotel'

urlpatterns = [
    path('', home, name='home'),
    path('dashboard', hotel_dashboard, name='dashboard'),
    path('update/<slug>', edit_hotel, name='update'),
    path('delete/<slug>', delete_hotel, name='delete'),
    path("search", search_hotel, name="search"),
    path('list-hotel', list_hotel, name='list_hotel'),
    path('hotel-detail/<slug>', hotel_detail, name = 'hotel_detail'),
    path('update-tc/<slug>', update_total_cost, name = 'update_total_cost'),
    path('hotel-cart', hotel_cart, name = 'hotel_cart'),
    
]

user/urls.py
from django.urls import path

from .views import *

app_name = 'user'

urlpatterns = [
    path('', dashboard, name='dashboard'),
]

user/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class CustomUser(AbstractUser):
    is_corporate = models.BooleanField(default=False)

    def __str__(self):
        return self.username

    def get_full_name(self):
        if self.first_name and self.last_name:
            return f"{self.first_name} {self.last_name}"
        else:
            return self.username

user/views.py
from django.shortcuts import render, HttpResponse

from .models import CustomUser
from hotel.models import Reservation

def dashboard(request):
    user = CustomUser.objects.get(username = request.user.username)
    reservation_record = Reservation.objects.filter(user = request.user, is_paid = True)

    context = {
        'user': user,
        'full_name': user.get_full_name,
        'reservation_record': reservation_record,
    }
    
    return render(request, "user/user_dashboard.html", context)

user/templates/user/user_dashboard.html
{% extends "base.html" %}

{% block title %}
{{ user }}'s Dashboard
{% endblock title %}

{% block content %}
<div class="profile-wrapper">
    <div class="profile-name">
        {{ full_name }}
    </div>
</div>

<div class="reservations">
    <div class="heading">
        <p>Reservation Record</p>
    </div>
    <div class="records">
        <table>
            <tr>
                <th>Hotel</th>
                <th>Check-In Date</th>
                <th>Check-Out Date</th>
                <th>Total Cost</th>
                <th>Created At</th>
            </tr>
            {% for record in reservation_record %}
            <tr>
                <td>
                    <a href="{% url 'hotel:hotel_detail' record.hotel.slug %}">
                        {{ record.hotel }}
                    </a>
                </td>
                <td>{{ record.check_in_date }}</td>
                <td>{{ record.check_out_date }}</td>
                <td>{{ record.total_cost }}</td>
                <td>{{ record.created_at }}</td>
            </tr>
            {% endfor %}
        </table>

    </div>
</div>

{% endblock content %}