base/urls.py
from django.urls import path

from .views import *

app_name = 'base'

urlpatterns = [
    path('', home, name = "home"),
    path('register/corporate', register, {'user_type': 'corporate'}, name = "register_corporate"),
    path('register', register, {'user_type': 'user'}, name = "register_user"),
    path('logout', logout_user, name = "logout_user"),
    path('login', login_user, name = "login_user"),
]

book_a_room/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve


handler404 = 'base.views.error_404_view'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('hotel/', include('hotel.urls')),
    path('user/', include('user.urls')),
    path('payment/', include('payment_gateway.urls')),
    re_path(r"^media/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT}),
    re_path(r"^static/(?P<path>.*)$", serve, {"document_root": settings.STATIC_ROOT}),
    path('summernote/', include('django_summernote.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

hotel/urls.py
from django.urls import path

from .views import home, hotel_dashboard, edit_hotel, delete_hotel, search_hotel, list_hotel, hotel_detail, update_total_cost, hotel_cart

app_name = 'hotel'

urlpatterns = [
    path('', home, name='home'),
    path('dashboard', hotel_dashboard, name='dashboard'),
    path('update/<slug>', edit_hotel, name='update'),
    path('delete/<slug>', delete_hotel, name='delete'),
    path("search", search_hotel, name="search"),
    path('list-hotel', list_hotel, name='list_hotel'),
    path('hotel-detail/<slug>', hotel_detail, name = 'hotel_detail'),
    path('update-tc/<slug>', update_total_cost, name = 'update_total_cost'),
    path('hotel-cart', hotel_cart, name = 'hotel_cart'),
    
]

user/urls.py
from django.urls import path

from .views import *

app_name = 'user'

urlpatterns = [
    path('', dashboard, name='dashboard'),
]

base/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from user.models import CustomUser

class CustomUserForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ['email', 'username', 'password1', 'password2']

        widgets = {
            'email': forms.EmailInput(attrs={'class': 'your-email-class'}),
            'username': forms.TextInput(attrs={'class': 'your-username-class'}),
            'password1': forms.PasswordInput(attrs={'class': 'your-password-class'}),
            'password2': forms.PasswordInput(attrs={'class': 'your-password-confirm-class'}),
        }

base/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.contrib.auth import authenticate, login, logout

from .forms import CustomUserForm
from hotel.models import Hotel


def error_404_view(request, exception):
    return render(request, 'custom_404.html', status=404)

def home(request):
    if request.user.is_authenticated and request.user.is_corporate:
        hotels = Hotel.objects.filter(hotelier__username=request.user.username)
    else:
        hotels = Hotel.objects.all()

    context = {"hotels": hotels}

    return render(request, "base/index.html", context)


# Create your views here.
def register(request, user_type):
    if request.method == "POST":
        custom_user_form = CustomUserForm(request.POST)

        if custom_user_form.is_valid():
            custom_user = custom_user_form.save(commit=False)

            if user_type == "corporate":
                custom_user.is_corporate = True
                print(user_type)

            custom_user_form.save()

            return redirect("base:login_user")

    custom_user_form = CustomUserForm()

    if user_type == "corporate":
        return render(
            request, "register_corporate.html", {"custom_user_form": custom_user_form}
        )
    if user_type == "user":
        return render(request, "register.html", {"custom_user_form": custom_user_form})


def logout_user(request):
    if request.user.is_authenticated:
        logout(request)

    return redirect("base:home")


def login_user(request):
    if request.method == "POST":
        try:
            fetch_username = request.POST["username"]
            fetch_password = request.POST["password"]
            user = authenticate(
                request, username=fetch_username, password=fetch_password
            )
            if user is not None:
                login(request, user)

                # Redirect to the 'next' URL if available, otherwise go to 'home'
                next_url = request.GET.get("next")
                if next_url:
                    return redirect(next_url)
                else:
                    return redirect("base:home")
            else:
                return HttpResponse("Invalid credentials.")
        except Exception as e:
            return HttpResponse("Error occur in login.")
    else:
        return render(request, "login.html")

templates/base.html
<!DOCTYPE html>
<html lang="en">

{% include "head_tag.html" %}

<body>
    <div class="app-container">
        {% include "nav.html" %}
                
        <div class="container-wrapper">
            {% block content %}

            {% endblock %}
        </div>
    </div>


</body>

</html>

templates/custom_404.html
<style>
    @import url("https://fonts.googleapis.com/css?family=Roboto+Mono");

    .center-xy {
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        position: absolute;
    }

    html,
    body {
        font-family: "Roboto Mono", monospace;
        font-size: 16px;
    }

    html {
        box-sizing: border-box;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
    }

    body {
        background-color: #000;
    }

    *,
    *:before,
    *:after {
        box-sizing: inherit;
    }

    .container {
        width: 100%;
    }

    .copy-container {
        text-align: center;
    }

    p {
        color: #fff;
        font-size: 24px;
        letter-spacing: 0.2px;
        margin: 0;
    }

    .go-home {
        font-size: 16px;
    }

    .go-home a {
        text-decoration: none;
        color: #666;
    }

    .go-home a:hover {
        text-decoration: dashed;
        color: #999;
    }

    

</style>
<div class="container">
    <div class="copy-container center-xy">
        <p>
            404, page not found.
        </p>
        <p class = "go-home"><a href = "{% url 'base:home' %}">click here to go home</p></a>

    </div>
</div>

templates/head_tag.html
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %}Book a Room</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">

    
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"
    integrity="sha256-oP6HI9z1XaZNBrJURtCoUT5SUnxFr8s3BzRl+cbzUq8=" crossorigin="anonymous"></script>
    
    <link href="{% static 'summernote/summernote-bs4.min.css' %}" rel="stylesheet">
    <script src="{% static 'summernote/summernote-bs4.min.js' %}"></script>
</head>

templates/login.html
{% extends "base.html" %}

{% block title %}Login{% endblock %}

{% block content %}


<title>TeamTrack</title>

<style>
  .LR-form #loginForm .error-message {
    font-size: 14px;
  }
</style>

<div class="main-content">
  <form method="post" action="">

    {% csrf_token %}


    <div class="loginregister-form-container">
      <div class="heading-content">
        <div class="heading-style">
          <p>Login</p>
        </div>
      </div>
      <div class="LR-form">
        <form id="loginForm" novalidate>
          <div class="form-group">
            <input type="text" placeholder="Username" id="username" name="username">
            <div id="usernameError" class="error-message"></div> <!-- Error message for username -->
          </div>

          <div class="div-space-top"></div>
          <div class="form-group">
            <input type="password" placeholder="Password" id="password" name="password" required>
            <div id="passwordError" class="error-message"></div> <!-- Error message for password -->
          </div>

          <div class="div-space-top"></div>

          <input type="submit" placeholder="" id="submitButton" value="Login">
          <p class="error-message error-report"></p>
        </form>
      </div>
    </div>
  </form>
</div>
{% endblock %}

templates/nav.html
<div class="navi position-sticky" style="z-index: 9;">
    <div class="navigation">
        <div class="nav-left-side">
            <a href="{% url 'base:home' %}" class="app-link heading">Book a Room</a>
        </div>

        <div class="search-container">
            <form method="get" action="{% url 'hotel:search' %}">
                <input type="text" name="query" class="search-bar" id="searchBar" placeholder="Search">
            </form>
        </div>

        <div class="nav-right-side" style="display: flex; gap:10px; align-items:center;">
            {% if request.user.is_authenticated %}
            {% if request.user.is_corporate %}
            <a href="{% url 'hotel:dashboard' %}">{{ request.user.username }}</a>
            <a href="{% url 'hotel:list_hotel' %}">List Your Hotel</a>
            {% else %}
            <a href="{% url 'user:dashboard' %}">{{ request.user.username }}</a>
            <a href="{% url 'hotel:hotel_cart' %}">Cart</a>
            {% endif %}
            <a href="{% url 'base:logout_user' %}">Logout</a>
            {% else %}
            <a href="{% url 'base:login_user' %}">Login</a>
            <a href="{% url 'base:register_user' %}">Register</a>
            {% endif %}
        </div>


    </div>
    <div class="custom-hr"></div>
</div>

templates/register.html
{% extends "base.html" %}


{% block content %}

<form action="" class="lr_form" method='post'>
    <h2>Register</h2>
    {% csrf_token %}

    {{ custom_user_form }}

    <button class="button-style">Submit</button>
    <br>
    <strong>OR</strong>
    <br>
    <a href="{% url 'base:register_corporate' %}" class="link">Register as Corporate</a>
</form>

{% endblock content %}

templates/register_corporate.html
{% include "nav.html" %}


<form action="" class="lr_form" method = 'post'>
    <h2>Register</h2>
    {% csrf_token %}

    {{ custom_user_form }}

    <button class="button-style">Submit</button>

    <p>or</p>
    <a href="{% url 'base:register_user' %}" class="link">Register as User</a>
</form>